include:
  # GitLoab
  - project_directory: ./gitlab
    path:
      - ./gitlab/docker-compose.gitlab.yml
    # env_file:
    #   - .env
  # Gitea
  - project_directory: ./gitea
    path:
      - ./gitea/docker-compose.gitea.yml
      # In production, use Postgres as DB backend instead
      # - ./gitea/docker-compose.gitea-with-postgres.yml
    # env_file:
    #   - .env
