include:
  # GitLoab
  - project_directory: ./gitlab
    path:
      - ./gitlab/docker-compose.gitlab.yml
  # Gitea
  - project_directory: ./gitea
    path:
      - ./gitea/docker-compose.gitea.yml
    # env_file:
    #   - ./__SECRET__env/portainer.env
